{
 "title": "Kokkos Job Summary",
 "time": { "from": "2022-03-16T14:05:00.628Z", "to": "2022-03-16T15:08:19.817Z" },
 "templating": {
  "list": [
   { "name": "JobID", "query": "<OMITTED JOB ID>" }
  ]
 },
 "panels": [
  {
   "title": "Application Kernel Throughput (Functions called per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "analysisModule": "kokkosProgressDSOS",
     "container": "eclipse",
     "filters": "job_id == $JobID",
     "frequency": 1,
     "schema": "kokkos_appmon4",
     "target": "*"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "analysisModule": "cpuTSDSOS",
     "container": "eclipse",
     "filters": "job_id == $JobID",
     "frequency": 1,
     "schema": "procstat_72",
     "target": "*"
    }
   ]
  },
  {
   "title": "Kernel Summary Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "analysisModule": "kokkosFuncTableDSOS",
     "container": "eclipse",
     "filters": "job_id == $JobID",
     "frequency": 1,
     "schema": "kokkos_appmon4",
     "target": "*"
    }
   ]
  },
  {
   "title": "Write Bytes on Nscratch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "analysisModule": "singleMetricRateTSDSOS",
     "container": "eclipse",
     "filters": "job_id == $JobID,fs_name=='nscratch'",
     "frequency": 1,
     "schema": "lustre_client",
     "target": "write_bytes.sum"
    }
   ]
  },
  {
   "title": "Active Memory Min/Max/Mean",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "analysisModule": "compMinMeanMaxDSOS",
     "container": "eclipse",
     "filters": "job_id == $JobID",
     "frequency": 1,
     "schema": "meminfo",
     "target": "Active"
    }
   ]
  }
 ]
}